export const WS_CONNECTION_START_ALL_ORDERS: "WS_CONNECTION_START_ALL_ORDERS" =
  "WS_CONNECTION_START_ALL_ORDERS";
export const WS_CONNECTION_SUCCESS_ALL_ORDERS: "WS_CONNECTION_SUCCESS_ALL_ORDERS" =
  "WS_CONNECTION_SUCCESS_ALL_ORDERS";
export const WS_CONNECTION_ERROR_ALL_ORDERS: "WS_CONNECTION_ERROR_ALL_ORDERS" =
  "WS_CONNECTION_ERROR_ALL_ORDERS";
export const WS_CONNECTION_CLOSED_ALL_ORDERS: "WS_CONNECTION_CLOSED_ALL_ORDERS" =
  "WS_CONNECTION_CLOSED_ALL_ORDERS";
export const WS_GET_ALL_ORDERS: "WS_GET_ALL_ORDERS" = "WS_GET_ALL_ORDERS";
