export const WS_CONNECTION_START_MY_ORDERS: "WS_CONNECTION_START_MY_ORDERS" =
  "WS_CONNECTION_START_MY_ORDERS";
export const WS_CONNECTION_SUCCESS_MY_ORDERS: "WS_CONNECTION_SUCCESS_MY_ORDERS" =
  "WS_CONNECTION_SUCCESS_MY_ORDERS";
export const WS_CONNECTION_ERROR_MY_ORDERS: "WS_CONNECTION_ERROR_MY_ORDERS" =
  "WS_CONNECTION_ERROR_MY_ORDERS";
export const WS_CONNECTION_CLOSED_MY_ORDERS: "WS_CONNECTION_CLOSED_MY_ORDERS" =
  "WS_CONNECTION_CLOSED_MY_ORDERS";
export const WS_GET_MY_ORDERS: "WS_GET_MY_ORDERS" = "WS_GET_MY_ORDERS";
